// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 68FsTXs8g8hH9RGmk7R9kt
// Component: 8nPGFfvsmr
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { Embed } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: PKldDYkH42/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_minimalist_about_me_page.module.css"; // plasmic-import: 68FsTXs8g8hH9RGmk7R9kt/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: 8nPGFfvsmr/css

export const PlasmicHomepage2__VariantProps = new Array();

export const PlasmicHomepage2__ArgProps = new Array();

function PlasmicHomepage2__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"XCP_BET_SCREEN_"}</title>
        <meta key="og:title" property="og:title" content={"XCP_BET_SCREEN_"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__adBxc)}>
            <p.PlasmicImg
              data-plasmic-name={"selection"}
              data-plasmic-override={overrides.selection}
              alt={""}
              className={classNames(sty.selection)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/selectioNpng.png",
                fullWidth: 1891,
                fullHeight: 637,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox___5Qdhg)} />

            <div className={classNames(projectcss.all, sty.freeBox__jz3AA)} />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__bqkKi)}>
            <p.PlasmicImg
              data-plasmic-name={"twServComp01"}
              data-plasmic-override={overrides.twServComp01}
              alt={""}
              className={classNames(sty.twServComp01)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/dupreeGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp02"}
              data-plasmic-override={overrides.twServComp02}
              alt={""}
              className={classNames(sty.twServComp02)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/nagaGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp03"}
              data-plasmic-override={overrides.twServComp03}
              alt={""}
              className={classNames(sty.twServComp03)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/dupreeGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp04"}
              data-plasmic-override={overrides.twServComp04}
              alt={""}
              className={classNames(sty.twServComp04)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/nagaGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__fM9Rl)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__itVMj)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowDupreEpng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__evbr)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowNagApng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ivlEn)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowDupreEpng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__yQb8)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowNagApng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___9CjK)}>
            <p.PlasmicImg
              data-plasmic-name={"twServComp012"}
              data-plasmic-override={overrides.twServComp012}
              alt={""}
              className={classNames(sty.twServComp012)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/dupreeGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp022"}
              data-plasmic-override={overrides.twServComp022}
              alt={""}
              className={classNames(sty.twServComp022)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/nagaGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp032"}
              data-plasmic-override={overrides.twServComp032}
              alt={""}
              className={classNames(sty.twServComp032)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/dupreeGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp042"}
              data-plasmic-override={overrides.twServComp042}
              alt={""}
              className={classNames(sty.twServComp042)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/nagaGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__yd9Nn)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__p1ReJ)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowDupreEpng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__xwRei)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowNagApng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ur5I)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowDupreEpng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__zhvEp)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowNagApng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__aksao)}>
            <p.PlasmicImg
              data-plasmic-name={"twServComp013"}
              data-plasmic-override={overrides.twServComp013}
              alt={""}
              className={classNames(sty.twServComp013)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/dupreeGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp023"}
              data-plasmic-override={overrides.twServComp023}
              alt={""}
              className={classNames(sty.twServComp023)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/nagaGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp033"}
              data-plasmic-override={overrides.twServComp033}
              alt={""}
              className={classNames(sty.twServComp033)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/dupreeGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              data-plasmic-name={"twServComp043"}
              data-plasmic-override={overrides.twServComp043}
              alt={""}
              className={classNames(sty.twServComp043)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"208px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/nagaGgif.gif",
                fullWidth: 1200,
                fullHeight: 1200,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___174Rp)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__jwPvR)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowDupreEpng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__uuYw)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowNagApng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__kPmdz)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowDupreEpng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___2POoG)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"200px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/betnowNagApng.png",
                fullWidth: 842,
                fullHeight: 230,
                aspectRatio: undefined
              }}
            />
          </div>

          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__eyk85)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/minimalist_about_me_page/images/inpuTpng3.png",
              fullWidth: 1891,
              fullHeight: 434,
              aspectRatio: undefined
            }}
          />

          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<form \r\n  method="POST" \r\n  action="https://script.google.com/macros/s/AKfycbwV2NLv6ac6Yee9tE9YzZwIvHVlM8vuT5XUIQzsedUBDc_GzWR22dlvsVo1aSKPh5_VYA/exec"\r\n>\r\n  <input name="Email" type="email" placeholder="INPUT-EMAIL" required>\r\n  <input name="Name" type="text" placeholder="INPUT-BET-PNUMBER-AS-SEEN-ABOVE" required>\r\n  <button type="submit">SUBMIT</button>\r\n</form>'
            }
          />

          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(projectcss.all, projectcss.a, sty.link)}
            component={Link}
            href={"/betrec_22_2"}
            platform={"nextjs"}
          >
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__jvXqu)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/minimalist_about_me_page/images/byclickingherEpng.png",
                fullWidth: 3150,
                fullHeight: 942,
                aspectRatio: undefined
              }}
            />
          </p.PlasmicLink>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "selection",
    "twServComp01",
    "twServComp02",
    "twServComp03",
    "twServComp04",
    "twServComp012",
    "twServComp022",
    "twServComp032",
    "twServComp042",
    "twServComp013",
    "twServComp023",
    "twServComp033",
    "twServComp043",
    "embedHtml",
    "link"
  ],

  selection: ["selection"],
  twServComp01: ["twServComp01"],
  twServComp02: ["twServComp02"],
  twServComp03: ["twServComp03"],
  twServComp04: ["twServComp04"],
  twServComp012: ["twServComp012"],
  twServComp022: ["twServComp022"],
  twServComp032: ["twServComp032"],
  twServComp042: ["twServComp042"],
  twServComp013: ["twServComp013"],
  twServComp023: ["twServComp023"],
  twServComp033: ["twServComp033"],
  twServComp043: ["twServComp043"],
  embedHtml: ["embedHtml"],
  link: ["link"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage2__ArgProps,
      internalVariantPropNames: PlasmicHomepage2__VariantProps
    });

    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    selection: makeNodeComponent("selection"),
    twServComp01: makeNodeComponent("twServComp01"),
    twServComp02: makeNodeComponent("twServComp02"),
    twServComp03: makeNodeComponent("twServComp03"),
    twServComp04: makeNodeComponent("twServComp04"),
    twServComp012: makeNodeComponent("twServComp012"),
    twServComp022: makeNodeComponent("twServComp022"),
    twServComp032: makeNodeComponent("twServComp032"),
    twServComp042: makeNodeComponent("twServComp042"),
    twServComp013: makeNodeComponent("twServComp013"),
    twServComp023: makeNodeComponent("twServComp023"),
    twServComp033: makeNodeComponent("twServComp033"),
    twServComp043: makeNodeComponent("twServComp043"),
    embedHtml: makeNodeComponent("embedHtml"),
    link: makeNodeComponent("link"),
    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
